apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: netperfs.app.example.com
spec:
  group: app.example.com
  names:
    kind: Netperf
    listKind: NetperfList
    plural: netperfs
    singular: netperf
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
              properties:
                name:
                  type: string
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                serverNode:
                  type: string
                clientNode:
                  type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
