apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nodeexporter
spec:
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
        - name: main
          image: prom/node-exporter:v1.4.0
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
