apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    release: test
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      {{- include "nginx.selectorLabels" . | nindent 6 }}
